name = "backend"
compatibility_date = "2024-08-24"

 [vars]
 DATABASE_URL = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGFiZDJlYzAtYmU0MS00N2Q1LWIwZWItMzgyODI5MDAwZTg0IiwidGVuYW50X2lkIjoiNDI4NzMxNGU0N2Q2NWIyOGY3YzEzZDFkN2U1ZDI5ODM5NzhlODFlZDFiN2M3MzI5ZjAwZmQ5ZGE4YWRiNzRkOCIsImludGVybmFsX3NlY3JldCI6IjY4YzgwMTE4LWJmOWUtNDMyMS1iZWU4LWQ1ZThlZjhkNDA1NiJ9.v3hz6pjactQ_IDLoyNhT9fD6TEbNl9g6UHoSi5c8EuU"
